name: Docker-Image

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the docker image
        run: make build

      - name: Publish to the registry
        run: |
          docker login docker.pkg.github.com --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"
          docker push docker.pkg.github.com/codelytv/php-ddd-example/php-ddd-example:${{ github.ref }}
